# Generated by Django 5.2.7 on 2025-10-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("department", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
