# Generated by Django 5.2.7 on 2025-10-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0002_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="fQrfSkEfe361srErd7pJIfXGbRjNuZKF",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
