# Generated by Django 5.2.7 on 2025-10-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0003_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="a0ya0T4okUyD1zm7eIWmU9uHn1sFAoks",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
